testing = true
host = "localhost"
port = 8080
url_prefix = "http://localhost"
frontend_url_prefix = "http://localhost:3000"
ethereum_endpoint = "http://localhost:8545"
ethereum_network = "local"
pull_ethereum = 2000  # msec
addresses_file = "../dist/deployed-addresses.json"
our_tax = 0.2

[secrets]
mother_hash = "Yeimawi2chohdeis1chiGhoochap?ooD8aeghee2tie(diN6ieB&aeng8eiRei_z"  # 64 bytes
ethereum_key_file = "ethereum.priv"
#ethereum_password = "ooP2Aigodee8OoM3"

[database]
conn_string = "host=localhost user=rserver password=123"

[stripe]
# The following are testing credentials:
public_key = "pk_test_51KQyqyJ2iRZ5a1XlawDeIDEBvPT88i81gRr1wy6b4j9gfNqkT5yhDZstUpIdjmovrnmD4nKkoQ5fmzhJhzZZvEZH00updo0A3n"
secret_key = "sk_test_51KQyqyJ2iRZ5a1XloMYifZLTVyNYr2BueN0YZEILU2CXHEwozbiDZRVXZVCjXZo8VqC91HEGb5ccnuJIz9XxSGiG00mjhUMsDi"
