host = "localhost"
port = 8080
url_prefix = "http://localhost"

[secrets]
ethreum_key_file = "supersecret.priv"
ethreum_password = "ooP2Aigodee8OoM3"

[database]
url = "postgres://rserver:123@localhost/rserver"
